### ISSUE TITLE
add a daemon to the snap

### ISSUE THREAD

**Issue by anonymouse64** [popey/matterbridge-snap#1]
The snap as it is isn't very useful to actually run on a Server or something because there is no service support so you have to manually run the snap as a user whenever you want it to run. It would be better if there was a daemon app in the snap, something like:

```yaml
system-usernames:
  snap_daemon: shared

apps:
  matterbridge-daemon:
    command: matterbridge -conf $SNAP_DATA/snap_daemon-dir/default.conf
    daemon: simple
    command-chain: 
      - drop-snap_daemon.sh
    plugs:
      - network
      - network-bind

parts:
  drop-snap-daemon:
    plugin: dump
    source: scripts
```

and then adding this inside `scripts/drop-snap_daemon.sh` in the repo:

```bash
#!/bin/bash
set -e

"$SNAP/usr/bin/setpriv" --clear-groups --reuid snap_daemon --regid snap_daemon -- "$@"
```

and then you'll need something silly in the install hook (and actually post-refresh hook too) to make a dir that is writable by `snap_daemon`, probably like:

```bash
#!/bin/bash
set -e

# create a snap_daemon writable dir
mkdir -p $SNAP_DATA/snap_daemon-dir
chown -R snap_daemon:snap_daemon $SNAP_DATA/snap_daemon-dir

# copy in some sensible default or maybe just an empty file for users to edit when deploying?
cp $SNAP/some-sensible-defaults.conf $SNAP_DATA/snap_daemon-dir/default.conf

# disable the daemon because it probably can't run without user configuration first
snapctl stop --disable "$SNAP_NAME.matterbridge-daemon"
```

then finally users would have to be instructed to modify $SNAP_DATA/snap_daemon-dir/default.conf with whatever configuration they actually want, then restart and enable the daemon with:

```
$ sudo snap start --enable matterbridge.matterbridge-daemon
```

Of course some of this could be simplified if you didn't want "securitiez to the max" and just ran the daemon as root and not snap_daemon, but from reading the description about only using certain plugs, etc. I assume it is rather sensitive for this to be security sensitive, and as such should run with minimal privilege as something other than root.
